### ISSUE TITLE
enumerating embeddings

### ISSUE THREAD

**Issue by jonaprieto** [szhorvat/IGraphM#107]
Is there a possibility or even something closer to
get all embeddings of a given graph to be planar?
From what I saw in the documentation so far, there
is a method to check if a given embedding corresponds
to a planar graph.

**Comment by szhorvat** [comment]
> Is there a possibility or even something closer to
> get all embeddings of a given graph to be planar?

There is no functionality to enumerate all embeddings, or all planar embeddings, of a planar graph. However, if the graph is 3-vertex-connected, then there is only one embedding. 

> From what I saw in the documentation so far, there
> is a method to check if a given embedding corresponds
> to a planar graph.

IGraph/M can check if an embedding is planar. Note that a planar graph can have several embeddings, some of which are planar, and some which are not.

----

I would like to keep the issue tracker for bug reports and feature request only. For future support questions, please use either the forum, https://igraph.discourse.group/, or https://mathematica.stackexchange.com/  Just add the appropriate tags, and I will respond eventually.
