### ISSUE TITLE
Support for macOS on arm64

### ISSUE THREAD

**Issue by tjeremie** [szhorvat/IGraphM#110]
**Describe the bug**
IGraphM doesn't seem compatible with the most recent version of Mathematica, see error below when I try installing it. Maybe it is because I am on the Apple Silicon (M1 chip) version of Mathematica.

**Error**
"The paclet \!\(\"IGraphM\"\) was successfully installed, but it will \
not be available in this session because it is not compatible with \
the currently running version of the Wolfram system."

**Version information**

 - IGraph/M version: v0.5.1
 - Mathematica version: 12.3.1 Mac OS X ARM (64-bit)
 - OS version: macOS 11.6

**Comment by szhorvat** [comment]
Sorry about the late response. I am aware of this, and an ARM-compatible release is in the works. Currently I have little free time, so the next release is behind schedule. I will close this issue once the new release is out.

**Comment by szhorvat** [comment]
Until then, please use the Intel version of Mathematica to be able to use IGraph/M. [Note that Mathematica itself lacks a few features on ARM.](https://mathematica.stackexchange.com/a/256980/12)

**Comment by julioparra** [comment]
Hi @szhorvat, I was wondering if there is an update about this issue. 
Thanks for this awesome package :)

**Comment by szhorvat** [comment]
@julioparra Thanks for the reminder. Can you please send me an email? I'll try to create a testing version for you.

**Comment by rohitn** [comment]
@szhorvat Same issue on "13.0.0 for Mac OS X ARM (64-bit) (December 3, 2021)"

**Comment by julioparra** [comment]
Hi Szabolcs,
  

  
Sure, I’d be happy to test.
  
I’m using Mathematica 13.0.0.
  

  
Best,
  
Julio
  
  
  
    
  

  
  
>

**Comment by julioparra** [comment]
Hi @szhorvat, I was wondering if you had the chance to create that testing version. Thanks!

**Comment by antononcube** [comment]
Is your time on fixing this quantifiable with money? (E.g. dollar amount per hour.)

**Comment by szhorvat** [comment]
Can you offer a full-time faculty job? Applying for those is taking up most of my time now ...

**Comment by antononcube** [comment]
:) I see. Well, unfortunately my academia relations are only through conferences or meetup talks...

**Comment by szhorvat** [comment]
Please do test interruptability, if possible.

For example:

```
Needs["IGraphM`"]

g = IGErdosRenyiGameGNM[50, 200, DirectedEdges -> True]
IGFeedbackArcSet[g]
```

This should take a very long time to complete. You can press Command-`.` or Alt-`.` to interrupt the calculation. It may take 1-2 seconds until interruption kicks in, but it should not require more than one press of Command-`.`.

**Comment by julioparra** [comment]
Hi @szhorvat,

Thank you so much for the update!
I tried installing it and it gives the following error:

![image](https://user-images.githubusercontent.com/1168064/170137220-48b6749b-367a-4eb6-bb8a-788b06d138c0.png)

I am using Mathematica 13.0.0

In[1]:= $Version
Out[1]= "13.0.0 for Mac OS X ARM (64-bit) (December 3, 2021)"

**Comment by rohitn** [comment]
Hi @szhorvat,

 I see the same error

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/25102/170140862-243bb3e7-51a2-4aee-88a7-5589659cad26.png">

`$Version`
"13.0.1 for Mac OS X ARM (64-bit) (January 28, 2022)"

**Comment by szhorvat** [comment]
Please re-download and try again.

**Comment by flaviolpp** [comment]
Hi @szhorvat,

I re-downloaded the package just now, and I am still getting the same error.

**Comment by szhorvat** [comment]
@flaviolpp Please uninstall the old one first, then re-install again. I did not bump the version number for this change, so a simple `PacletInstall` will not reinstall it. Lesson learned, I'll bump the version for each new prerelease as I share them.

**Comment by flaviolpp** [comment]
I was not able to uninstall it with the PacletUninstall. It says Mathematica cannot find IGraphM.
Instead, I deleted the paclet manually from "~/Library/Mathematica/Paclets/Repository/", which I believe achieves the same goal. Am I correct? Not sure Mathematica registers the paclet elsewhere ... 

In any case, I did it and it returned the same error after PacletInstall.

**Comment by szhorvat** [comment]
Sorry about that, there was a typo in the accepted SystemID value. Please try again.

**Comment by flaviolpp** [comment]
There you go

![Screenshot 2022-05-25 at 13 45 03](https://user-images.githubusercontent.com/7165450/170265129-e4e91272-e1b9-4537-9b55-5828669a6f37.png)

All worked fine. :)
Also, this one

![Screenshot 2022-05-25 at 13 46 09](https://user-images.githubusercontent.com/7165450/170265317-9ad6112c-a3c0-4f9f-bfe5-f7c6b69f8570.png)

went without problems, the operation was aborted on the first attempt.

**Comment by julioparra** [comment]
Working like a charm!

![Screen Shot 2022-05-25 at 09 52 42](https://user-images.githubusercontent.com/1168064/170318343-4a8cf690-6dd6-4d0c-ab13-ba6e38ae35d0.png)

![Screen Shot 2022-05-25 at 09 54 06](https://user-images.githubusercontent.com/1168064/170318480-56bf9dfd-e45c-4c00-9b01-b532f7b9fd11.png)

Thanks again!

**Comment by szhorvat** [comment]
Please just use it as normal, or explore the new features based on the [changelog](https://github.com/szhorvat/IGraphM/blob/master/CHANGELOG.md), and if anything seems off, let me know. This'll help us reach to the final release more quickly.

**Comment by szhorvat** [comment]
A release is out now, closing this.
