### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by flaviolpp** [szhorvat/IGraphM#112]
Hi there, 

been using iGraph for a long time on Mac with intel. 
Do you have any plans to add support for Apple Silicon? I read on another page you had an experimental version with support for M1 that you would release soon (but that post was made a while ago)

Anyway, that would be amazing, I would be very grateful. 
Thank you!

**Comment by szhorvat** [comment]
Would you be willing in helping with creating binaries for that platform, if needed?

**Comment by szhorvat** [comment]
Closing in favour of #110

**Comment by flaviolpp** [comment]
Hi szhorvat, sure anything I can help and that is in my reach.

**Comment by szhorvat** [comment]
Please follow issue #110 for further updates.
