### ISSUE TITLE
IGGraphEditor: limit aspect ratio (or "narrowness") of editor

### ISSUE THREAD

**Issue by szhorvat** [szhorvat/IGraphM#116]
When launching `IGGraphEditor` with a path graph, it produces a very narrow display that:

 - is difficult to work with
 - cuts off labels

<img width="508" alt="image" src="https://user-images.githubusercontent.com/1212871/176434109-4c3120f8-451a-41f5-abd1-788cf9f43d59.png">

We should think about how to improve this. Of course dragging vertices outside the frame extends the frame, but it might still be a good idea to set limits of the minimum height / width.

**Comment by kubaPod** [comment]
If the initial range's aspect ratio will exceed a limit (10) then the range will be 'squared':
![image](https://user-images.githubusercontent.com/15227576/176882922-ad57c6eb-b3f2-46b6-978d-05ec3d897de1.png)
