### ISSUE TITLE
IGGraphEditor: Command-clicking to create a new vertex shows resize frame

### ISSUE THREAD

**Issue by szhorvat** [szhorvat/IGraphM#120]
**Describe the bug**

With the graph editor, Alt-clicking (Command-clicking) to create a new editor with an existing graph. Dragging vertices works fine, and so does clicking a vertex to select it for adding an edge. But Command-clicking to create a new vertex shows the orange resize frame. Clicking to discard an edge that is about to be added does the same.

**To Reproduce**

Evaluate `IGGraphEditor[IGShorthand["1-2-3-1"]]`

**Version information**

0.6.0

**Comment by kubaPod** [comment]
@szhorvat using Pane's ResizeArea will give more control the price will be more code lines and ux decisions that will need to be made. Time spent will not be worth it at this point, let's get back to this in the future, unless my patch is not robust enough.
