### ISSUE TITLE
Cannot open LTemplate`LTemplatePrivate`. 

### ISSUE THREAD

**Issue by Juddd** [szhorvat/IGraphM#25]
I don't know why I cannot use the package in my official PC.When I run ``<< IGraphM```,it will give an error information like this
![](http://o8aucf9ny.bkt.clouddn.com/2016-06-06-19-31-23.png)
But my dormitory PC can use it normally.Actually the package have been placed in right way.
![](http://o8aucf9ny.bkt.clouddn.com/2016-06-06-19-37-15.png)

**Comment by szhorvat** [comment]
This problem is mentioned in the README, under Troubleshooting.  Does the solution there apply to you?

**Comment by Juddd** [comment]
Thanks for your so soon response.And I made it.

**Comment by szhorvat** [comment]
Great!  I'm closing this issue then.  Side note: I just release version 0.2.1, you might want to use that instead of 0.2.0.

**Comment by Juddd** [comment]
I have already downloaded it when you updated it actually. :) I have to thank for your effort.
