### ISSUE TITLE
Cannot open LTemplate`LTemplatePrivate` 

### ISSUE THREAD

**Issue by Juddd** [szhorvat/IGraphM#35]
I do all step as [this page](https://github.com/szhorvat/IGraphM#installation).But I get this error in formation when I Get this package.
![111](https://cloud.githubusercontent.com/assets/10048069/21110382/e93ab032-c0d7-11e6-9cbc-60d557e548b4.png)

But I can run `IGDocumentation[]` normally to get the documemtation.It's a new bug or my misoperation?

ps:My version is:
`$Version`

> "11.0.1 for Microsoft Windows (64-bit) (September 20, 2016)"

And the zip download from [here](https://cloud.githubusercontent.com/assets/10048069/21110498/6090d526-c0d8-11e6-891d-2a0b95665b24.png).

**Comment by szhorvat** [comment]
I seem to have missed this.

Please always download from the releases page:

https://github.com/szhorvat/IGraphM/releases

Do not clone the repo or download from the main page here: https://github.com/szhorvat/IGraphM  That's only for development.

If you get the zip file from the releases page, that will solve the problem.
