### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mdzzm** [szhorvat/IGraphM#36]
Error Message:

In[3]:= << IGraphM`

LibraryFunction::notfound: Symbol IGraphM not found.

Loading failed, trying to recompile ...

Current directory is: C:\Users\xxx\Desktop\IGraphM-master\IGraphM\LibraryResources\Source

Unloading library IGraphM ...
 Generating library code ...

Compiling library code ...

call "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

cl.exe /LD /O2 /MT /EHsc /wd4244 /DNOMINMAX  /I "D:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\IncludeFiles\C" /I "D:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Links\MathLink\DeveloperKit\Windows-x86-64\CompilerAdditions\mldev64\include" /I "C:\msys64\home\%USERNAME%\local\include" /I "C:\ProgramData\Mathematica\Applications\LTemplate\IncludeFiles" "C:\Users\xxx\Desktop\IGraphM-master\IGraphM\LibraryResources\Source\LTemplate-IGraphM.cpp" "C:\Users\xxx\Desktop\IGraphM-master\IGraphM\LibraryResources\Source\IGlobal.cpp" /link  /implib:"C:\Users\xxx\Desktop\IGraphM-master\IGraphM\LibraryResources\Windows-x86-64\Working-pc-of-zj-172-11660-1\IGraphM.lib"  /LIBPATH:"D:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Links\MathLink\DeveloperKit\Windows-x86-64\CompilerAdditions\mldev64\lib" /LIBPATH:"D:\Program Files\Wolfram Research\Mathematica\11.0\SystemFiles\Libraries\Windows-x86-64"  "ml64i4m.lib" "C:\msys64\home\%USERNAME%\local\lib\libigraph.dll.a" /out:"C:\Users\xxx\Desktop\IGraphM-master\IGraphM\LibraryResources\Windows-x86-64\Working-pc-of-zj-172-11660-1\IGraphM.dll"

C:\Users\xxx\Desktop\IGraphM-master\IGraphM\LibraryResources\Windows-x86-64\Working-pc-of-zj-172-11660-1>call "D:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64 
ÓÃÓÚ x64 \[Micro]Ä Microsoft (R) C/C++ ÓÅ»¯\[PlusMinus]àÒëÆ/ 19.00.23918 \[Degree]æ
\[Degree]æÈ¨ËùÓÐ(C) Microsoft Corporation¡£\[PlusMinus]£ÁôËùÓÐÈ¨Àû¡£

LTemplate-IGraphM.cpp
c:\users\xiaozhujie\desktop\igraphm-master\igraphm\libraryresources\source\IGCommon.h(5): fatal error C1083: ÎÞ\[CenterDot]¨\.b4ò¿ª\[Degree]üÀ¨ÎÄ¼þ: ¡\[Degree]igraph/igraph.h¡\[PlusMinus]: No such file or directory
IGlobal.cpp
c:\users\xxx\desktop\igraphm-master\igraphm\libraryresources\source\IGCommon.h(5): fatal error C1083: ÎÞ\[CenterDot]¨\.b4ò¿ª\[Degree]üÀ¨ÎÄ¼þ: ¡\[Degree]igraph/igraph.h¡\[PlusMinus]: No such file or directory
ÕýÔÚÉú\.b3É\.b4úÂë...

CreateLibrary::cmperr: Compile error: c:\users\xxx\desktop\igraphm-master\igraphm\libraryresources\source\IGCommon.h(5): fatal error C1083: ÎÞ\[CenterDot]¨\.b4ò¿ª\[Degree]üÀ¨ÎÄ¼þ: ¡\[Degree]igraph/igraph.h¡\[PlusMinus]: No such file or directory

CreateLibrary::cmperr: Compile error: c:\users\xxx\desktop\igraphm-master\igraphm\libraryresources\source\IGCommon.h(5): fatal error C1083: ÎÞ\[CenterDot]¨\.b4ò¿ª\[Degree]üÀ¨ÎÄ¼þ: ¡\[Degree]igraph/igraph.h¡\[PlusMinus]: No such file or directory

 LibraryFunction::notfound: Symbol IGraphM not found.

 Cannot load or compile library. \[FreakedSmiley] Aborting.

Out[3]= $Aborted

**Comment by szhorvat** [comment]
I cannot do anything with this unless you give me details about your setup (OS, platform, Mathematica version, etc.).  See the Troubleshooting section of the readme file on what information I need.

This happens either when your platform is not supported (unlikely) or when you did not install IGraph/M correctly. Do NOT clone the repository.  That is only for development.

Download the zip file from the releases page and use that: https://github.com/szhorvat/IGraphM/releases

**Comment by mdzzm** [comment]
Thank you for your help! I downloaded the release version and it works. I'm new to github and librarylink  of mathematica. I think I've done something stupid…

**Comment by szhorvat** [comment]
OK, great!  A new version is in the works.  It will be released shortly after Mathematica 11.1 (whenever that happens), and it will be required for compatibility with that version of Mathematica.  So if you can give any feedback or suggestions, this is a good time.
