### ISSUE TITLE
IGraphM compatibility with ParallelTable?

### ISSUE THREAD

**Issue by shubharajkharel** [szhorvat/IGraphM#51]
When running codes of following format, IGraphM functions gives either warning or error:

            f=Funtion[{input}, MathematicaFunction@someIGraphMFunctions]
            ParallelTable[ f[input], iterator]

Following is an example:
![image](https://user-images.githubusercontent.com/30309305/28403183-94fe3806-6cf1-11e7-919e-f527c8143270.png)

There is no errors/warnings if IGraphM output is not processed by Mathematica's function however:
         
            f=Funtion[{input}, someIGraphMFunctions]
            ParallelTable[ f[input], iterator]

Following is an example:
![image](https://user-images.githubusercontent.com/30309305/28403352-5549729c-6cf2-11e7-976c-8277361eb2dd.png)

Thank you for creating IGraphM. It has been very useful. 
-Shubha

**Comment by szhorvat** [comment]
You need to load the package on all subkernels in addition to the main kernel. You can use:

    ParallelNeeds["IGraphM`"]

in addition to

    Needs["IGraphM`"]

This is not specific to IGraph/M.  It works this way with any package.

**Comment by shubharajkharel** [comment]
It worked. Thanks.
