### ISSUE TITLE
Error in IGIsomorphicQ when comparing some multigraphs

### ISSUE THREAD

**Issue by julioparra** [szhorvat/IGraphM#53]
Most of the time it works, but for certain multigraphs it returns the following error

`IGraphM::error: topology.c:1109 - Invalid edge color vector length`

`IGraphM::error: igraph returned with error: Invalid value`

`LibraryFunctionError["LIBRARY_FUNCTION_ERROR", 6]`

For instance when I compare these two graphs

`exg1=Graph[{3 <-> 2, 2 <-> 5, 5 <-> 4, 2 <-> 1, 6 <-> 5, 6 <-> 5, 2 <-> 1, 
 1 <-> 3, 4 <-> 6, 4 <-> 3}];`

`exg2=Graph[{5 <-> 3, 2 <-> 1, 3 <-> 2, 4 <-> 5, 6 <-> 4, 3 <-> 2, 2 <-> 1, 
 4 <-> 5, 6 <-> 4, 1 <-> 6}];`

**Comment by szhorvat** [comment]
Thank you for the report. 

I believe this was a bug in the core igraph library, which was fixed recently: https://github.com/igraph/igraph/issues/1010

The fix is included in the latest IGraph/M prerelease (0.3.92). Please use that.

**Comment by julioparra** [comment]
Great! Thanks for the swift response! Keep up the good work 👍
