### ISSUE TITLE
IGMakeLattice: more input is needed?

### ISSUE THREAD

**Issue by PedroSapichu** [szhorvat/IGraphM#54]
Hi!

Whenever I try to make a lattice with IGMakeLattice, I get an error asking for more input. What else do I need to provide? I tried the example of the documentation:

![error](https://user-images.githubusercontent.com/25947175/32407596-dfd4b8cc-c161-11e7-9024-c7c83107a6af.png)

Thanks!,
Pedro

**Comment by szhorvat** [comment]
How did you type that `[`?  It does not look like the usual `[` character.  Try copying and pasting this directly:

    IGMakeLattice[{3,4}, GraphStyle -> "VintageDiagram"]

Does it work?

**Comment by PedroSapichu** [comment]
Holly cow! It was a silly mistake, thanks!
