### ISSUE TITLE
does not generate BuildSettings.m when using PacletInstall[]

### ISSUE THREAD

**Issue by eherrmann10** [szhorvat/IGraphM#71]
Dear Szabolcs,
I have tried to install IGraphM on my Mac with Mathematica 11.2, but whenever I use the PacletInstall[IGraphM-0.3.100.paclet] it does NOT generate the BuildSettings.m file in the ..../Library/Mathematica/Paclets/Repository/IGraphM-0.3.100 
folder. As you mention, this usually is meant to indicate that there is something incompatible with the system, but I don't understand what that might be. 

When I copy the BuildSettings.m file to this location by hand and modify the paths to libigraph.a and the other 2 libraries, Mathematica outputs some compilation errors once I try to load <<IGraphM`.

Here would be an example of that error message (see below). I would really appreciate your help. Thanks a lot for your effort in maintaining this package.

Best regards,
Enrico

In[45]:= << IGraphM`

During evaluation of In[45]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[45]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[45]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[45]:= General::stop: Further output of File::fstr will be suppressed during this calculation.

During evaluation of In[45]:= Loading failed, trying to recompile ...

During evaluation of In[45]:= Current directory is: /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source

During evaluation of In[45]:= Unloading library IGraphM ...

During evaluation of In[45]:= Generating library code ...

During evaluation of In[45]:= Compiling library code ...

During evaluation of In[45]:= /usr/bin/clang -dynamiclib -o "/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/MacOSX-x86-64-libc++/Working-Enricos-MacBook-Pro-45703-3043255168-5/IGraphM.dylib" -m64 -fPIC -O2 -mmacosx-version-min=10.9 -framework Foundation -mmacosx-version-min=10.9 -std=c++11 -mmacosx-version-min=10.9 -flto=thin  -I"/Applications/Mathematica.app/Contents/SystemFiles/IncludeFiles/C" -I"/Applications/Mathematica.app/Contents/SystemFiles/Links/MathLink/DeveloperKit/MacOSX-x86-64/CompilerAdditions" -I"/usr/local/include" -I"/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LTemplate/IncludeFiles" "/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp" "/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGlobal.cpp" "/usr/local/lib/libigraph.a" "/usr/local/lib/libgmp.a" "/usr/local/lib/libemon.a" -F"/Applications/Mathematica.app/Contents/SystemFiles/Links/MathLink/DeveloperKit/MacOSX-x86-64/CompilerAdditions" -L"/usr/local/lib"  -framework "mathlink" -lc++ 2>&1

During evaluation of In[45]:= In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:6:
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGlobal.h:10:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGCommon.h:255:63: error: use of undeclared identifier 'igraph_malloc'
        igraph_vector_t *vec = static_cast<igraph_vector_t *>(igraph_malloc(sizeof(igraph_vector_t)));
                                                              ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:218:9: error: unknown type name 'igraph_realize_degseq_t'
        igraph_realize_degseq_t ig_method;
        ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:221:29: error: use of undeclared identifier 'IGRAPH_REALIZE_DEGSEQ_SMALLEST'
        case 0: ig_method = IGRAPH_REALIZE_DEGSEQ_SMALLEST; break;
                            ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:222:29: error: use of undeclared identifier 'IGRAPH_REALIZE_DEGSEQ_LARGEST'
        case 1: ig_method = IGRAPH_REALIZE_DEGSEQ_LARGEST; break;
                            ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:223:29: error: use of undeclared identifier 'IGRAPH_REALIZE_DEGSEQ_INDEX'
        case 2: ig_method = IGRAPH_REALIZE_DEGSEQ_INDEX; break;
                            ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:261:28: error: use of undeclared identifier 'igraph_from_prufer'
        igConstructorCheck(igraph_from_prufer(&graph, &vec.vec));
                           ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:284:28: error: no matching function for call to 'igraph_extended_chordal_ring'
        igConstructorCheck(igraph_extended_chordal_ring(&graph, n, &w.mat, directed));
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/igraph/igraph_constructors.h:69:5: note: candidate function not viable: requires 3 arguments, but 4 were provided
int igraph_extended_chordal_ring(igraph_t *graph, igraph_integer_t nodes, 
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:323:9: error: unknown type name 'igraph_random_tree_t'
        igraph_random_tree_t ig_method;
        ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:326:25: error: use of undeclared identifier 'IGRAPH_RANDOM_TREE_PRUFER'
            ig_method = IGRAPH_RANDOM_TREE_PRUFER;
                        ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:329:25: error: use of undeclared identifier 'IGRAPH_RANDOM_TREE_LERW'
            ig_method = IGRAPH_RANDOM_TREE_LERW;
                        ^
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:345:29: error: use of undeclared identifier 'IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE_UNIFORM'; did you mean 'IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE'?
        case 3: ig_method = IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE_UNIFORM; break;
                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                            IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE
/usr/local/include/igraph/igraph_constants.h:85:9: note: 'IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE' declared here
               IGRAPH_DEGSEQ_SIMPLE_NO_MULTIPLE } igraph_degseq_t;
               ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:593:17: error: use of undeclared identifier 'igraph_is_tree'; did you mean 'igraph_tree'?
        igCheck(igraph_is_tree(&graph, &res, nullptr, imode));
                ^~~~~~~~~~~~~~
                igraph_tree
/usr/local/include/igraph/igraph_constructors.h:63:5: note: 'igraph_tree' declared here
int igraph_tree(igraph_t *graph, igraph_integer_t n, igraph_integer_t children, 
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:593:32: error: cannot initialize a parameter of type 'igraph_t *' (aka 'igraph_s *') with an rvalue of type 'const igraph_t *' (aka 'const igraph_s *')
        igCheck(igraph_is_tree(&graph, &res, nullptr, imode));
                               ^~~~~~
/usr/local/include/igraph/igraph_constructors.h:63:27: note: passing argument to parameter 'graph' here
int igraph_tree(igraph_t *graph, igraph_integer_t n, igraph_integer_t children, 
                          ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:867:17: error: use of undeclared identifier 'igraph_rewire_directed_edges'; did you mean 'igraph_rewire_edges'?
        igCheck(igraph_rewire_directed_edges(&graph, prob, loops, out ? IGRAPH_OUT : IGRAPH_IN));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                igraph_rewire_edges
/usr/local/include/igraph/igraph_games.h:137:5: note: 'igraph_rewire_edges' declared here
int igraph_rewire_edges(igraph_t *graph, igraph_real_t prob, 
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:898:17: error: no matching function for call to 'igraph_canonical_permutation'
        igCheck(igraph_canonical_permutation(&graph, col.length() == 0 ? nullptr : &colvec.vec, &vec.vec, blissIntToSplitting(splitting), nullptr));
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/igraph/igraph_topology.h:265:5: note: candidate function not viable: requires 4 arguments, but 5 were provided
int igraph_canonical_permutation(const igraph_t *graph, igraph_vector_t *labeling, 
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:908:17: error: no matching function for call to 'igraph_isomorphic_bliss'
        igCheck(igraph_isomorphic_bliss(
                ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/igraph/igraph_topology.h:267:5: note: candidate function not viable: requires 9 arguments, but 10 were provided
int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:921:17: error: no matching function for call to 'igraph_isomorphic_bliss'
        igCheck(igraph_isomorphic_bliss(
                ^~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/igraph/igraph_topology.h:267:5: note: candidate function not viable: requires 9 arguments, but 10 were provided
int igraph_isomorphic_bliss(const igraph_t *graph1, const igraph_t *graph2,
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:937:17: error: no matching function for call to 'igraph_automorphisms'
        igCheck(igraph_automorphisms(&graph, colors.length() == 0 ? nullptr : &colors.vec, blissIntToSplitting(splitting), &info));
                ^~~~~~~~~~~~~~~~~~~~
/usr/local/include/igraph/igraph_topology.h:273:5: note: candidate function not viable: requires 3 arguments, but 4 were provided
int igraph_automorphisms(const igraph_t *graph,
    ^
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/LTemplate-IGraphM.cpp:7:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:952:17: error: use of undeclared identifier 'igraph_automorphism_group'
        igCheck(igraph_automorphism_group(&graph, colors.length() == 0 ? nullptr : &colors.vec, &list.list, blissIntToSplitting(splitting), nullptr));
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGlobal.cpp:7:
In file included from /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGlobal.h:10:
/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGCommon.h:255:63: error: use of undeclared identifier 'igraph_malloc'
        igraph_vector_t *vec = static_cast<igraph_vector_t *>(igraph_malloc(sizeof(igraph_vector_t)));
                                                              ^
1 error generated.

During evaluation of In[45]:= CreateLibrary::cmperr: Compile error: /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IGCommon.h:255:63: error: use of undeclared identifier 'igraph_malloc'

During evaluation of In[45]:= CreateLibrary::cmperr: Compile error: /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:218:9: error: unknown type name 'igraph_realize_degseq_t'

During evaluation of In[45]:= CreateLibrary::cmperr: Compile error: /Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.3.100/LibraryResources/Source/IG.h:221:29: error: use of undeclared identifier 'IGRAPH_REALIZE_DEGSEQ_SMALLEST'

During evaluation of In[45]:= General::stop: Further output of CreateLibrary::cmperr will be suppressed during this calculation.

During evaluation of In[45]:= LibraryFunction::notfound: Symbol IGraphM not found.

During evaluation of In[45]:= Cannot load or compile library. \[FreakedSmiley] Aborting.

Out[45]= $Aborted

**Comment by szhorvat** [comment]
You should _never_ try to manually modify the installation in any way. That is not necessary and it will introduce issues that will mislead us when trying to debug this.

I can't tell for sure, but what you see very likely happens either because of a botched previous installation event (and incomplete removal afterwards) or because the package files were modified in some way.

Please uninstall IGraph/M using `PacletUninstall["IGraphM"]`.

Now evaluate ``FindFile["IGraphM`"]``. Let me know the output. It should be `$Failed`.

Now download the paclet again, and install it using `PacletInstall` (or just use the installation script which downloads it automatically).

Evaluate each of the following in turn, and copy the results here:

    FindFile["IGraphM`"]

    Needs["IGraphM`"]

    IGraphM`Developer`GetInfo[]

Finally, let me know what hardware you are running on, and what is your operating system (with exact version).

**Comment by eherrmann10** [comment]
Dear Szabolcs,
Thanks for your quick response. 

I'm running Mac OSX
Darwin Kernel Version 17.7.0: 
x86_64

I've uninstalled and installed the Paclet, 
`In[89]:= FindFile["IGraphM`"]`

`
Out[89]= "/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-\
0.3.100/Kernel/init.m"
`

`In[90]:= Needs["IGraphM`"]`

`In[91]:= IGraphM`Developer`GetInfo[]`

`Out[91]= IGraphM`Developer`GetInfo[]``

For the GetInfo[] I only get the trivial output back. Btw. when I run the code segment you have on GitHub for the auto-download, I also get an error message. 

> In[93]:= updateIGraphM[]

During evaluation of In[93]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[93]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[93]:= FromJSON::libload: -- Message text not found --

During evaluation of In[93]:= FromJSON::init: -- Message text not found --

During evaluation of In[93]:= Import::fmterr: Cannot import data as JSON format.

During evaluation of In[93]:= First::normal: Nonatomic expression expected at position 1 in First[$Failed].

During evaluation of In[93]:= Lookup::invrl: The argument First[$Failed] is not a valid Association or a list of rules.

During evaluation of In[93]:= First::normal: Nonatomic expression expected at position 1 in First[$Failed].

During evaluation of In[93]:= Lookup::invrl: The argument First[$Failed] is not a valid Association or a list of rules.

During evaluation of In[93]:= First::normal: Nonatomic expression expected at position 1 in First[$Failed].

During evaluation of In[93]:= General::stop: Further output of First::normal will be suppressed during this calculation.

During evaluation of In[93]:= Lookup::invrl: The argument First[$Failed] is not a valid Association or a list of rules.

During evaluation of In[93]:= General::stop: Further output of Lookup::invrl will be suppressed during this calculation.

During evaluation of In[93]:= StringJoin::string: String expected at position 2 in Downloading IGraph/M <>Lookup[First[json$141724],tag_name]<> ....

During evaluation of In[93]:= URLSave::invurl: Lookup[First[Lookup[First[json$141724],assets]],browser_download_url] is not a valid URL

During evaluation of In[93]:= URLSave::invurl: Lookup[First[Lookup[First[json$141724],assets]],browser_download_url] is not a valid URL

Out[93]= $Failed

**Comment by szhorvat** [comment]
Thanks for posting the results! Can you please do the same steps again, but make sure to restart Mathematica right after uninstalling IGraph/M?

I forgot to mention this last time, and you probably didn't see my later edit.

So:

 - Uninstall it
 - Restart Mathematica
 - install it and run the commands I asked for

This time the output will not be trivial.

**Comment by eherrmann10** [comment]
So I restarted Mathematica after uninstalling IGraph/M and generate the following output:

Needs["PacletManager`"]

PacletInstall["/Users/eh10/Documents/amplitudes_packages/IGraphM-0.3.100.paclet"]

Out[3]= PacletManager`Paclet[
"Name" -> "IGraphM", "Version" -> "0.3.100", 
 "MathematicaVersion" -> "10.0+", 
 "Description" -> "IGraph/M \[Dash] the igraph interface for \
Mathematica.", "Creator" -> "Szabolcs Horvát <szhorvat@gmail.com>", 
 "URL" -> "http://szhorvat.net/mathematica/IGraphM", 
 "Thumbnail" -> "Logo.png", 
 "SystemID" -> {"MacOSX-x86-64", "Windows-x86-64", "Linux-x86-64"}, 
 "Extensions" -> {{
   "Kernel", "Root" -> ".", "Context" -> "IGraphM`"}, {
   "LibraryLink"}, {
   "Documentation", "MainPage" -> "Tutorials/IGDocumentation"}}, 
 "Location" -> "/Users/eh10/Library/Mathematica/Paclets/Repository/\
IGraphM-0.3.100"]

In[4]:= FindFile["IGraphM`"]

Out[4]= "/Users/eh10/Library/Mathematica/Paclets/Repository/IGraphM-0.\
3.100/Kernel/init.m"

In[5]:= Needs["IGraphM`"]

During evaluation of In[5]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[5]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[5]:= File::fstr: File specification  is not a string of one or more characters.

During evaluation of In[5]:= General::stop: Further output of File::fstr will be suppressed during this calculation.

During evaluation of In[5]:= Loading failed, trying to recompile ...

During evaluation of In[5]:= Recompile::build: No build settings found. Please check BuildSettings.m.

During evaluation of In[5]:= Cannot load or compile library. \[FreakedSmiley] Aborting.

Out[5]= $Aborted

In[6]:= IGraphM`Developer`GetInfo[]

Out[6]= IGraphM`Developer`GetInfo[]

**Comment by szhorvat** [comment]
This is a problem I did not encounter before. It is going to take several exchanges to solve it. Could you please send me an email (szhorvat at gmail dot com), so we can continue the discussion there?

**Comment by szhorvat** [comment]
I prepared a troubleshooting notebook that will gather more information about your system. Once I have your email address, I will send it to you.

**Comment by szhorvat** [comment]
Just checking to see if you sent the email—I have not received it and I would very much like to resolve this problem.

**Comment by eherrmann10** [comment]
just sent you an email, thanks for your quick responses.

**Comment by szhorvat** [comment]
Summary of our e-mail discussion:

 - The problem was due to a misconfiguration on the user's machine, which resulted in spurious messages being issued when using certain file access functions. IGraph/M aborted loading because it assumed that the messages indicated a loading failure. After resettig Mathematica's configuration, IGraph/M works fine.
 - When loading was aborted, ``IGraphM`Developer`GetInfo[]` was not available. This is now fixed.
 - `BuildSettings.m` is not supposed to be present in the distributed version of IGraph/M. It is only used during development.
