### ISSUE TITLE
Upgrade to IGraphM v0.3.108 did not resolve problem with MM v11.2 Documentation Center

### ISSUE THREAD

**Issue by jbishop-intven** [szhorvat/IGraphM#86]
Problem:

I used the command
`Get["https://raw.githubusercontent.com/szhorvat/IGraphM/master/IGInstaller.m"]`
to install the IGraphM package to MM v11.2, which then caused an issue with the MM Documentation Center. It no longer showed me search results (even for built-in functions when clicking the info icon in the front end). 

I read on GitHub that this was an issue some release versions of IGraphM (I'm sorry I did not note which version I had installed), so I used
`PacletUninstall["IGraphM"]`
and then the equivalent of
`PacletInstall["~/Download/IGraphM-0.3.108.paclet"]`
on my Windows 10 machine to get a pre-release version of IGraphM that I expected to solve the issue. However, even after restarting Mathematica, the issue with the Documentation Center persists. Thanks!

----

```
in: IGraphM`Developer`GetInfo[]

out: "Mathematica version: 
11.2.0 for Microsoft Windows (64-bit) (September 11, 2017); Release number: 0

Package version: 
0.3.108 (December 17, 2018)

Package location: 
C:\\Users\\jbishop\\AppData\\Roaming\\Mathematica\\Paclets\\Repository\\IGraphM-0.3.108\\Kernel\\init.m

Library location:
C:\\Users\\jbishop\\AppData\\Roaming\\Mathematica\\Paclets\\Repository\\IGraphM-0.3.108\\LibraryResources\\Windows-x86-64\\IGraphM.dll

IGVersion[]:
IGraph/M 0.3.108 (December 17, 2018)
igraph 0.8.0-pre+8e840c5c (Dec 17 2018)
Microsoft Windows (64-bit)

Build settings:
None

Operating system:
Microsoft Windows [Version 10.0.16299.904]"
```

**Comment by szhorvat** [comment]
There is a known problem with Mathematica: uninstalling a paclet that contains documentation may cause the documentation not to work for the rest of the session. It is possible that this is what is affecting you.  Note that this is a bug in Mathematica, not in IGraph/M.

I suggest the following steps:

 1. `PacletUninstall["IGraphM"]`
 2. Restart Mathematica (not just the kernel, but fully quit it, then start it again).
 3. Verify (and confirm to me) that the documentation center works

 4. Now install IGraph/M again, just as you did before: `Get["https://raw.githubusercontent.com/szhorvat/IGraphM/master/IGInstaller.m"]`.  

 5. Does the documentation center work now?

 6. If it does not, fully restart Mathematica.  Does it work now?

**Comment by jbishop-intven** [comment]
Thank you very much, Szabolcs, for helping me with a bug not of your own making. I can confirm that at step 3. the Documentation Center works.

However, at step 5. and step 6., the Documentation Center does not work.
----
Mathematica version: 
11.2.0 for Microsoft Windows (64-bit) (September 11, 2017); Release \
number: 0

Package version: 
0.3.108 (December 17, 2018)

Package location: 
C:\Users\jbishop\AppData\Roaming\Mathematica\Paclets\Repository\I\
GraphM-0.3.108\Kernel\init.m

Library location: 
C:\Users\jbishop\AppData\Roaming\Mathematica\Paclets\Repository\I\
GraphM-0.3.108\LibraryResources\Windows-x86-64\IGraphM.dll

IGVersion[]: 
IGraph/M 0.3.108 (December 17, 2018)
igraph 0.8.0-pre+8e840c5c (Dec 17 2018)
Microsoft Windows (64-bit)

Build settings: 
None

**Comment by szhorvat** [comment]
Thanks for the response. That seems unusual. Can you clarify in what way it does not work (precise steps: "I do this, expect A, but B happens")?  

I do not usually use Windows, and I cannot reproduce the problems in steps 7 and 8 on a Mac. (I can see the problem in step 3, which is the bug I was referring to.) I will need to investigate on Windows, and will get back to you.

**Comment by jbishop-intven** [comment]
No problem, sorry to have not made it clear in the original issue!

I type a function, for example 'NumberQ', then I press the F1 key (shortcut for Doc Center, maybe `Cmd-?` on a Mac) or click the "info symbol" from the front-end context menu.

I expect the Doc Center to open to help page for "Built-in Symbol > NumberQ".

Instead I get "Your search - NumberQ - in Documentation Center did not match any documents." Furthermore, a search for "NumberQ" in the search box of the Doc Center returns "Your search - NumberQ - in Documentation Center did not match any documents."

**Comment by szhorvat** [comment]
I was able to reproduce it, which means that there's a reasonable chance that I can find a fix.

The problem is specific to 11.2, neither 11.1 nor 11.3 have it. It might also be Windows-specific. This suggests that it's a bug in Mathematica.

That said, it is completely unacceptable that IGraph/M should break the documentation center, and I will look for a solution.

I will be travelling until the end of the week and will be able to look at this afterwards.

Thanks again for reporting this. Actually, I am surprised that no one else has complained.

**Comment by jbishop-intven** [comment]
Ha, no problem, thank you for looking at the issue, although I, for one, do not need a speedy resolution here. Thanks again!

**Comment by szhorvat** [comment]
I actually have a hunch about what may be wrong.

Please try this for me:

Fully close Mathematica.

Open the location of the IGraphM paclet:

```mma
pinfo = PacletInformation["IGraphM"]
SystemOpen@Lookup[pinfo, "Location"]
```

Now go in the `Documentation\English` subdirectory and delete the `TextSearchIndex` directory there.

Start Mathematica, open the doc center, and search for something (doesn't matter what).  Now a window should appear that tells you that documentation indices are being generated.  When it's done, everything should work fine.

Let me know if this worked for you.

**Comment by jbishop-intven** [comment]
Yes, that did the trick. Nice work, and thank you!

**Comment by szhorvat** [comment]
Version 0.3.109 is now released, and includes the fix to this issue.

**Comment by szhorvat** [comment]
@jbishop-intven Something went wrong with the fix for this issue and it regressed again. The latest version, 0.3.112, is verified free of the problem. Please upgrade (also to get other fixes).
