### ISSUE TITLE
Plotting communities while defining layouts like in Python

### ISSUE THREAD

**Issue by Vurgit** [szhorvat/IGraphM#99]
Compared with python-igraph, igraphm can plot boundaries,but layoutsin Mathematica are not that nice.  Once plotting communities, the layout of graphs will be lost and the edges and topology are not clear.  When keeping the layout and plotting communities with different colors, the boundaries and edges between communities will vanish. Hoping to add a feature of plotting boundaries, keeping the layout of the graph and keeping the edges between communities at the mean time.

**Comment by szhorvat** [comment]
Would you mind posting a comparison screenshot to clarify what you mean exactly?

**Comment by Vurgit** [comment]
Are the screenshots visible? I met problems when uploading screenshots before.
A typical python-igraph plot of communities is like this:
![Python-igraph communities plot](https://user-images.githubusercontent.com/56619134/71571551-d0772c00-2b15-11ea-9b5f-37c762b02d50.png)
Communities are plotted with different colors and layouts can be defined. In this picture the layout is defined as kawai_kamada. But no boundaries can be created.
In igraphm, lets take examples in the documentation:
![igraphm communities plot](https://user-images.githubusercontent.com/56619134/71571721-af630b00-2b16-11ea-9062-6a5333c72ee4.png)
There are boundaries but the layout is totally ruined. Layouts can only be plotted without partition of communities like this:
![igraphm layout plot](https://user-images.githubusercontent.com/56619134/71571759-e9cca800-2b16-11ea-85c9-c561c29171ce.png)
The layout is nice but no communities or boundaries.
Is there any solution to keep communities, layout and boundaries at the same time?

**Comment by szhorvat** [comment]
Note that `CommunityGraphPlot` is a visualization feature built-in to Mathematica. It is not provided by IGraph/M. It can merely be used to plot any community structure.  It is also not the only way to visualize communities. If you want to colour vertices, you can use `HighlightGraph`, which is also a built-in function.

```
g = ExampleData[{"NetworkGraph", "FamilyGathering"}];

cl = IGCommunitiesMultilevel[g]

HighlightGraph[g, cl["Communities"], VertexSize -> Large]
```

![image](https://user-images.githubusercontent.com/1212871/71575087-e07a1600-2aeb-11ea-9c57-9a49253df41a.png)

**Comment by Vurgit** [comment]
Yes Mr Horvat thats a nicely plotted graph with communities, but I mean is it possible to add boundaries based on a graph like this in igraphm? There doesnt seem to be such features. Could that be added in the next version?&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Szabolcs Horvát"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 下午5:06
收件人:&nbsp;"szhorvat/IGraphM"<IGraphM@noreply.github.com&gt;;
抄送:&nbsp;"yangyang"<980182570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [szhorvat/IGraphM] Plotting communities while defining layouts like in Python (#99)




Note that CommunityGraphPlot is a visualization feature built-in to Mathematica. It is not provided by IGraph/M. It can merely be used to plot any community structure.  It is also not the only way to visualize communities. If you want to colour vertices, you can use HighlightGraph, which is also a built-in function.
 g = ExampleData[{"NetworkGraph", "FamilyGathering"}]; cl = IGCommunitiesMultilevel[g] HighlightGraph[g, cl["Communities"], VertexSize -&gt; Large]

**Comment by szhorvat** [comment]
I can see why that would be a desirable feature, but it is not obvious how to make it work well in practice. Depending on the graph layout, the vertices belonging to the same community may not be drawn contiguously in space.

Try re-evaluating this a few times after removing the `SeedRandom` command:

```mma
SeedRandom[12345];
g = RandomGraph[{50, 80}, VertexSize -> 1];
HighlightGraph[g, IGCommunitiesEdgeBetweenness[g]["Communities"]]
```

![image](https://user-images.githubusercontent.com/1212871/71581326-f0522400-2b04-11ea-99fc-40d35292a037.png)

**Comment by szhorvat** [comment]
A half-workaround with `CommunityGraphPlot` could be to disable edge bundling:

```mma
SeedRandom[12345];
g = RandomGraph[{50, 80}, VertexSize -> 1];
CommunityGraphPlot[g, IGCommunitiesEdgeBetweenness[g]["Communities"], 
 EdgeShapeFunction -> "Line"]
```

![image](https://user-images.githubusercontent.com/1212871/71581462-a584dc00-2b05-11ea-8052-f356be48821d.png)

**Comment by Vurgit** [comment]
Oh thank you so much Dr&nbsp;Horvát thats exactly what I want




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Szabolcs Horvát"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 晚上8:09
收件人:&nbsp;"szhorvat/IGraphM"<IGraphM@noreply.github.com&gt;;
抄送:&nbsp;"yangyang"<980182570@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [szhorvat/IGraphM] Plotting communities while defining layouts like in Python (#99)




A half-workaround with CommunityGraphPlot could be to disable edge bundling:
 SeedRandom[12345]; g = RandomGraph[{50, 80}, VertexSize -&gt; 1]; CommunityGraphPlot[g, IGCommunitiesEdgeBetweenness[g]["Communities"],   EdgeShapeFunction -&gt; "Line"]
